### ISSUE TITLE
0.3.1 checklist

### ISSUE THREAD

**Issue by 2AUK** [2AUK/pyRISM#3]
Checklist of features being added to 0.3.1

- [X] Lambda cycling (removed this from Rust implementation, slipped my mind to put it back in)
- [x] Better long output (currently doesn't work on some systems; overall looks janky. Tables are better.)
- [x] working PSE-n closure (currently a half-finished macro)
- [x] ~LMV solver~ Pushed to later release
- [X] MDIIS Refactor
- [x] Better reporting on solver information (solution times, iterations, etc. will be better for analysis in the long run)
- [x] Developer docs (or the start there of)
- [x] Comprehensive test suite for benchmarking

**Comment by 2AUK** [comment]
Merged 0.3.1-dev branch for new release
